### ISSUE TITLE
Improve the UI of the Interface

### ISSUE THREAD

**Issue by Akshat2Jain** [Akshat2Jain/Todo_FirebaseFirestore#1]
## Any contributions will be appreciated!!

![Screenshot from 2022-07-15 14-16-45](https://user-images.githubusercontent.com/101265586/179192392-a1a7c3da-01e0-4e66-994b-49e250c7a359.png)

**Comment by davidmicahdaniels** [comment]
okay

**Comment by Akshat2Jain** [comment]
> Contributor

Lets connect on twitter
Follow me on @easyakshat

**Comment by davidmicahdaniels** [comment]
okay follow back
