### ISSUE TITLE
add a media querie for button 

### ISSUE THREAD

**Issue by Akshat2Jain** [Akshat2Jain/Todo_FirebaseFirestore#2]
## Add media querie for button for max width 375px

`
@media screen and (max-width: 375px) {
    button{
        padding-left:1px ;
        width: 15%;
    }
  }
`

## add it in styles.css

**Comment by Dun-sin** [comment]
can i do this?

**Comment by davidmicahdaniels** [comment]
add the media query at each breakpoints

**Comment by Akshat2Jain** [comment]
> can i do this?

Ya sure

**Comment by Akshat2Jain** [comment]
> davidmicah123

Plz create a pull request

**Comment by davidmicahdaniels** [comment]
okay
