### ISSUE TITLE
add hover effects to the li's

### ISSUE THREAD

**Issue by Akshat2Jain** [Akshat2Jain/Todo_FirebaseFirestore#3]
## Add a hover effect to lists

`li:hover{
    background: rgb(202, 195, 195);
}
li:nth-child(even):hover{
    background: rgb(202, 195, 195);
}
`

**Comment by Aspireve** [comment]
Hey @Akshat2Jain could I do this?

**Comment by Aspireve** [comment]
Actually I've already done it should I push it?

**Comment by davidmicahdaniels** [comment]
okay
